[package]
name = "app"
version = "1.0.0"
authors = ["Teaclave"]
build = "build.rs"

[dependencies] # You can specify the features you need for urts, such as global_exit and global_init
sgx_types = { path = "../sdk/sgx_types" }
sgx_urts  = { path = "../sdk/sgx_urts" }
